-- Cria a trigger

CREATE TRIGGER PROCESSADOR_datahora ON PROCESSADOR

FOR UPDATE

AS

BEGIN

UPDATE PROCESSADOR SET ultima_atualizacao = GETDATE()

FROM PROCESSADOR

INNER JOIN INSERTED ON PROCESSADOR.idProcessador = INSERTED.idProcessador

END