CREATE TABLE LOG_USO(
    ID_USO_COMPONENTE INT PRIMARY KEY NOT NULL,
    UPTIME VARCHAR(50),
    PROCESSES FLOAT,
    THREADS FLOAT,
    USO_LOAD FLOAT,
    SPEED FLOAT,
    INTERRUPTS FLOAT,
    CONTEXT_SWITCHES FLOAT,
    COMP_SIZE FLOAT,
    COMP_USED FLOAT,
    COMP_AVAILABLE FLOAT
);