CREATE TABLE COMPONENTE (
    ID_COMPONENTE INT PRIMARY KEY NOT NULL,
    NM_COMPONENTE VARCHAR (50),
    IDENTIFICADOR VARCHAR(50),
    FAMILIA VARCHAR(50),
    ID_PROCESSADOR VARCHAR(50),
    FORNECEDOR VARCHAR(50),
    STEPPING VARCHAR(50),
    MODEL VARCHAR(50),
    DESCRIBE VARCHAR(100),
    PARTICAO INT,
    FK_ID_LOG_USO INT,

    FOREIGN KEY (FK_ID_LOG_USO) REFERENCES LOG_USO(ID_USO_COMPONENTE) 
);