CREATE TABLE MAQUINA_FISICA (
    ID_MAQUINA INT PRIMARY KEY NOT NULL,
    SISTEMA_OPERACIONAL VARCHAR(100),
    SERIAL_NUMBER VARCHAR(100),
    MANUFACTURER VARCHAR(100),
    NOME VARCHAR(100),
    VERSAO VARCHAR(50),
    MODEL VARCHAR(100),
    MC_ADRESS VARCHAR (50),
    DOMAIN_NAME VARCHAR(50),
    HOST_NAME VARCHAR(50),
    GATEWAY_IPV4  VARCHAR(10),
    GATEWAY_IPV6 VARCHAR(50),
    DESCRIBE VARCHAR(100),
    FK_MAQUINA_VIRTUAL_ID_VM INT,
    FK_COMPONENTE_ID_COMPONENTE INT,

    FOREIGN KEY (FK_MAQUINA_VIRTUAL_ID_VM) REFERENCES MAQUINA_VIRTUAL (ID_VM),
    FOREIGN KEY (FK_COMPONENTE_ID_COMPONENTE) REFERENCES COMPONENTE(ID_COMPONENTE)
);