CREATE TABLE EMPRESA (
    ID_EMPRESA INT PRIMARY KEY NOT NULL,
    NM_EMP VARCHAR(50),
    CNPJ INT,

    FK_ESTABELECIMENTO_ID_ESTABELECIMENTO INT, 

    FOREIGN KEY (FK_ESTABELECIMENTO_ID_ESTABELECIMENTO) REFERENCES ESTABELECIMENTO(ID_ESTABELECIMENTO)
);