CREATE TABLE ESTABELECIMENTO (
    ID_ESTABELECIMENTO INT PRIMARY KEY NOT NULL,
    NM_ESTABELECIMENTO VARCHAR(50),
    FK_LUCRO_ID_LUCRO INT,
    FK_AREA_ID_AREA INT,

    FOREIGN KEY (FK_LUCRO_ID_LUCRO) REFERENCES LUCRO(ID_LUCRO),
    FOREIGN KEY (FK_AREA_ID_AREA) REFERENCES AREA(ID_AREA)
);