CREATE TABLE AREA (
    ID_AREA INT PRIMARY KEY NOT NULL,
    NM_AREA VARCHAR(50),
    
    FK_USUARIO_ID_USUARIO INT,
    FK_MAQUINA_FISICA_ID_MAQUINA_FISICA  INT,
    FK_RELATORIO_ID_RELATORIO INT,

    FOREIGN KEY (FK_USUARIO_ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (FK_MAQUINA_FISICA_ID_MAQUINA_FISICA) REFERENCES MAQUINA_FISICA (ID_MAQUINA),
    FOREIGN KEY (FK_RELATORIO_ID_RELATORIO) REFERENCES RELATORIO (ID_RELATORIO)
);